### ISSUE TITLE
Modifying dataTransfert.effectAllowed

### ISSUE THREAD

**Issue by rrouxyoobic** [akserg/ng2-dnd#10]
Hello ! Thank you for this really useful module.

I'm facing a problem when trying to change the effect when dragging and dropping.
Is there any way to change the config by passing an argument like 'effectAllowed' ?
For example, something like that : 

```
<div dnd-sortable-container [sortableData]="el" [dropZones]="['zone1']">
    <div *ngFor="#e of el; #ie=index" dnd-sortable [sortableIndex]="ie" [effectAllowed]="copy">
        <div>{{e}}</div>
    </div>
</div>
```

Thanks in advance !

**Comment by akserg** [comment]
I will do it in next release.

**Comment by rrouxyoobic** [comment]
Perfect, thanks !
When have you planed to do it ? (no pressure, just to have an idea :) )

**Comment by akserg** [comment]
I'm a bit busy for now but I schedule to release no later than this weekend.

**Comment by rrouxyoobic** [comment]
Perfect, thanks !

**Comment by akserg** [comment]
Hi,
Sorry for delay.

**Comment by akserg** [comment]
I have added input properties:
- effectAllowed
- effectCursor
Can you check and close if this one was sorted.

**Comment by akserg** [comment]
Hi,

Can I close this issue?

**Comment by rrouxyoobic** [comment]
Hi,

Yes, thanks for the update !
