### ISSUE TITLE
Drop not work with angular2 2.1 

### ISSUE THREAD

**Issue by VaibhavNarkhede** [akserg/ng2-dnd#103]
Hello akserg,
I am not able to install latest 2.2.1, it is released or still in development
because i can drag the div but not able to drop it in version 2.1.1.

**Comment by akserg** [comment]
Hi @VaibhavNarkhede 
The latest version of ng2-dnd is 2.1.1. Can you tell me a bit more about you environment such web browser and angular2 versions? Do you use SystemJS or Webpack? Did you tried examples:
- with SystemJS in (ng2-systemjs-demo)[https://github.com/akserg/ng2-systemjs-demo]
- with Webpack in (ng2-webpack-demo)[https://github.com/akserg/ng2-webpack-demo]

**Comment by VaibhavNarkhede** [comment]
Hello akserg,
Thanks for your quick reply, Please find below my environment details 
Web Browser - Google Chrome but also tried on IE and Firefox
Angular2 Veriosn - 2.2.3
I am using Webpack and also tried examples given in the https://github.com/akserg/ng2-dnd like (3. Use Drag-and-Drop operations with no code and 4. Restriction Drag-and-Drop operations with drop zones)
but only drag feature is working drop is not working

**Comment by oslanier** [comment]
hello,
I have the same problem with angular 2.2.3, any solution?

**Comment by Con3jo** [comment]
same here :/

**Comment by dabruns** [comment]
I have the same problem. Is a workaround available?

**Comment by zeljko-bulatovic** [comment]
Same here.. 

There is no any error in console, drag is working, and drop is not working.. 

Angular: 2.3.1
ng2-dnd: 2.2.1

Any updates about this issue?

**Comment by akserg** [comment]
I think there are mistakes in the README. Please have a look source code in
https://github.com/akserg/ng2-webpack-demo/blob/master/src/app/dnd/dnd.component.html.
You can test the online version of the working code here:
http://akserg.github.io/ng2-webpack-demo.

**Comment by zeljko-bulatovic** [comment]
Thanks for quick response! So far, example which i need is working!

**Comment by akserg** [comment]
Thank you, @zeljko-bulatovic 
I will update the README shortly.

**Comment by akserg** [comment]
I have updated the README from working [examples](https://github.com/akserg/ng2-webpack-demo/tree/master/src/app/dnd).

**Comment by vikram-raj** [comment]
I am using angular 2.4.8 and ng2-dnd  2.0.1 and I am facing the same issue. Drag is working but drop is not working.
