### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by yanbo-zhou-ila** [akserg/ng2-dnd#109]
Hello,

I am new to the ng2-dnd. Following the instructions step by step, added the module to my project. But, when I "npm start" my project,  always get 404 on ng2-dnd. In Chrome, the dev tool shows.

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-dnd
	Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-dnd

Any advice will be really appreciated.

Thanks,
Yanbo

**Comment by yanbo-zhou-ila** [comment]
I am using:
1. Angular 2 @2.4.2
2. npm @3.10.9
3. node.js @7.2.0

yanbo

**Comment by yanbo-zhou-ila** [comment]
Reading the other threads through, is it caused by the dynamic component that I am using?

yanbo

**Comment by akserg** [comment]
Hi @yanbo-zhou-ila 
May you have a chance to look at [ng2-systemjs-demo](https://github.com/akserg/ng2-systemjs-demo) where you can find working example.

**Comment by yanbo-zhou-ila** [comment]
Still not working.

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/src/app.module
	Error: XHR error (404 Not Found) loading http://localhost:3000/src/app.module
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (https://npmcdn.com/zone.js@0.7.2:851:29) [<root>]
	    at Zone.runTask (https://npmcdn.com/zone.js@0.7.2:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (https://npmcdn.com/zone.js@0.7.2:332:33) [<root>]
	Error loading http://localhost:3000/src/app.module as "./app.module" from http://localhost:3000/src/main.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (https://npmcdn.com/zone.js@0.7.2:851:29) [<root>]
	    at Zone.runTask (https://npmcdn.com/zone.js@0.7.2:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (https://npmcdn.com/zone.js@0.7.2:332:33) [<root>]
	Error loading http://localhost:3000/src/app.module as "./app.module" from http://localhost:3000/src/main.js

**Comment by akserg** [comment]
Ok. I will have a look on weekend.

**Comment by yanbo-zhou-ila** [comment]
Thanks and looking forward to any findings.

**Comment by akserg** [comment]
I have updated README. There are 100% working examples for SystemJS and Webpack. 
Can you somehow share your code if it still doesn't work?

**Comment by yanbo-zhou-ila** [comment]
The SystemJS demo is working now. Thanks,

**Comment by akserg** [comment]
Ok.
Good luck.
