### ISSUE TITLE
Can't bind to 'dragEnabled' since it isn't a known native property 

### ISSUE THREAD

**Issue by stmart76** [akserg/ng2-dnd#11]
I have tried to get this working and followed all the steps but I am getting
Can't bind to 'dragEnabled' since it isn't a known native property

**Comment by akserg** [comment]
Any source code?

**Comment by stmart76** [comment]
I am using aspnet core 1.0
I have copied ng2-dnd to my wwwroot/lib and included this in the html 
<script src="~/lib/ng2-dnd/bundles/ng2-dnd.js"></script>
also
    <script>
        System.config({
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js'
          },
          "/ng2-dnd": { "defaultExtension": "js" }
        }
      });
      System.import('app/main')
            .then(null, console.error.bind(console));
    </script>

in my component
import {DND_PROVIDERS,DND_DIRECTIVES} from 'ng2-dnd/ng2-dnd';

@Component({
    templateUrl: 'app/manageappcodes/manage-app-codes.component.html',
    directives: [ROUTER_DIRECTIVES, PartCodeComonent, DND_DIRECTIVES],
    providers: [DND_PROVIDERS]
})

it is from the most basic example

extract as follows
    <div class="col-sm-3">
        <div class="panel panel-success">
            <div class="panel-heading">Available to drag</div>
            <div class="panel-body" dnd-draggable [dragEnabled]="true">
                <div class="panel panel-default" >
                    <div class="panel-body">
                        <div>Drag Me</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

**Comment by akserg** [comment]
I recommend you remove '~' from the path to ng2-dnd.js file:
```
<script src="/lib/ng2-dnd/bundles/ng2-dnd.js"></script>
```
Don't forget to add reference to ng2-dnd styleshit:
```
<link rel="stylesheet" type="text/css" href="/lib/ng2-dnd/ng2-dnd.css">
```

And finally I believe you have included references on Angular files into your index.html file as well:
```
<script src="/lib/angular2/bundles/angular2-polyfills.js"></script>
<script src="/lib/es6-shim/es6-shim.min.js"></script>
<script src="/lib/systemjs/dist/system.src.js"></script>
<script src="/lib/rxjs/bundles/Rx.js"></script>
<script src="/lib/angular2/bundles/angular2.dev.js"></script>
<script src="/lib/angular2/bundles/router.dev.js"></script>
```

**Comment by stmart76** [comment]
Thanks but i do not think this is the issue, these are drag and drop from VS solution explorer, all the files have a ~ and every one you mentioned is coming down, I also added the css.

I just tried the shopping cart example.  I got the same error, so i removed that property binding, then I got a similar issue with another property

EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'dragData' since it isn't a known native property ("or="#product of availableProducts" class="panel panel-default"
                     dnd-draggable  [ERROR ->][dragData]="product"

**Comment by stmart76** [comment]
I have just noticed my transpiled js does not look right at all, this has to be the issue.

**Comment by stmart76** [comment]
I think i see the issue. I will reply once i fix it.

**Comment by stmart76** [comment]
I think i see my issue.  my files are getting compiled into a nested folder, gulp issue I think.  Nothing to do with your component at all.  I am sure now I can get it going. Thank you for your time and your good work.

**Comment by akserg** [comment]
Not a problem. Just let me know how is going and close this issue if it solved from your side.

**Comment by stmart76** [comment]
My tsconfig had     "outDir": "wwwroot" which was creating app/app so the application was picking up an old transpiled file.
I then had a system loader issue
I changed to 
`
import {DND_PROVIDERS,DND_DIRECTIVES } from '../../node_modules/ng2-dnd/ng2-dnd';
`
and 

`<script>
        System.config({
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js'
          },
          "/../../node_modules/ng2-dnd/": { "defaultExtension": "js" }
        }
      });
      System.import('app/main')
            .then(null, console.error.bind(console));
    </script>`

now no errors.
Thanks
