### ISSUE TITLE
How to use dnd-droppable and dnd-draggable conditionally?

### ISSUE THREAD

**Issue by v891** [akserg/ng2-dnd#114]
Hi All,

I am trying to use dnd-droppable and dnd-draggable conditionally, but some reason it is not working as I expected, I added below condition to dnd-droppable. 
`[attr.dnd-droppable] = "isDroppable ? true : null"`. 
Here is the [plnkr](https://plnkr.co/edit/7RA1ZbeXRRmgFabXwjW5?p=preview) example. Is there something that I am doing wrong? Please help me.

Much Thanks!

**Comment by akserg** [comment]
Hi @v891 

There are two sides involved in drag and drop process, so you can use different properties to manage them:
- The `dragEnabled` for draggable components: `dnd-draggable [dragEnabled]="true"`
- The `dropEnabled` for droppable components: `dnd-droppable [dropEnabled]="true"`
You can find example [here](https://github.com/akserg/ng2-dnd#3-use-drag-and-drop-operations-with-no-code).
