### ISSUE TITLE
allowDropFunction is not a function

### ISSUE THREAD

**Issue by v891** [akserg/ng2-dnd#115]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

* **What is the current behavior?**
If I add [allowDrop] property to my div tag, I am seeing `TypeError: this.allowDrop is not a function` error

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.
Here is the [plnkr link](https://plnkr.co/edit/Q1QZWtZiljGhkgC3huDZ?p=preview). I added [allowDrop] to shopping basket.

Thanks!

**Comment by magomarlon** [comment]
Same problem here, some solution?

**Comment by akserg** [comment]
I will have a look tomorrow.

**Comment by akserg** [comment]
The `allowDropFunction` must return a function. It accepts the `dragData` as a parameter and must return the boolean:
```
allowDropFunction(): any {
  return (dragData: any) => true;
}
```
You can test the `dragData` value inside the function to return the boolean result dynamically. Find out more in [this](https://github.com/akserg/ng2-dnd#6-use-a-custom-function-to-determine-where-dropping-is-allowed) example.
