### ISSUE TITLE
styling the clone element without  affecting the actual dragged element

### ISSUE THREAD

**Issue by piyushbageria** [akserg/ng2-dnd#12]
Hi, first of all i would like to thank you for this useful module.

As per my requirement  i have to give custom style to the the cloned element without affecting the actual dragged element.I was trying to add  style  to "dnd-drag-start" class as this class is being added to the dragged element while dragging.but it changes the style for both the actual element and cloned element.

it would be very nice if you can help me to solve this issue.

**Comment by akserg** [comment]
Hi,
I will have a look for the rest of the week.

**Comment by akserg** [comment]
Hi,
Can you give me an example to play with, may be a plunkr project?

**Comment by akserg** [comment]
Hi,

Any updates?
