### ISSUE TITLE
Support Angular 4?

### ISSUE THREAD

**Issue by Pikadili83** [akserg/ng2-dnd#134]
After upgrading to Angular 4 a got:
ng2-dnd@2.2.2 requires a peer of @angular/core@^2.4.4 but none was installed
Do you plan to support Angular 4?

**Comment by akserg** [comment]
It supports both 2 and 4 version of Angular as it was merged from this [PR](https://github.com/akserg/ng2-dnd/pull/130):
`"@angular/core": "^2.4.4 || ^4.0.0"`
