### ISSUE TITLE
On Sort Event Functionality

### ISSUE THREAD

**Issue by hennessyben** [akserg/ng2-dnd#139]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Create a way for you to trigger an event on sort. Currently, this function seems less enhanced thatn drag and drop.

* **What is the current behavior?**
Currently, there is an issue using (onDropSuccess) for Sorting.

* **What is the expected behavior?**
On Sorting, there should be a way to trigger functions to take place - update arrays/save data/etc.

* **What is the motivation / use case for changing the behavior?**
I want to be able to update my array to store the current positioning of each row within the sortable container.

- Angular version: 4
- Browser: [Chrome XX ]

**Comment by Derekjohnson277** [comment]
Any solutions to this?

**Comment by Oscarsgc** [comment]
How did you solved this @hennessyben ???

**Comment by ClaytonBrawley** [comment]
I'd like to see a solution to this, as well.

**Comment by mlg-mbojcic** [comment]
any solutions?

**Comment by tpettrov** [comment]
Any solution ?

**Comment by Oscarsgc** [comment]
I couldn't find any solution, instead of that, I'm using _onDropSuccess_ to keep the order and sort my items using a function.

**Comment by hennessyben** [comment]
Hi, I did this to fix it. Made change to index.umd.js to allow Sortable Container to send Drag Data to function:

Line 1003-1004

//this._dragDropService.onDragSuccessCallback.emit(this._dragDropService.dragData); Previous does not allow Sortable to transfer drag and drop data

this._dragDropService.onDragSuccessCallback.emit({ dragData: this._dragDropService.dragData, mouseEvent: event });
