### ISSUE TITLE
How to setup a developing environment

### ISSUE THREAD

**Issue by Abrissirba** [akserg/ng2-dnd#149]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[x] question about the decisions made in the repository

How do you set up a developing environment for this project? I looked at the package.json but I can't figure out how to launch a server where I can try the components and directives. I only found how to run unit tests and how to build the output.

**Comment by akserg** [comment]
Hi Marcus,

As far as I understand you are looking for a demo project demonstrates the usage of NG2-DND module. Have a look at [Demo](https://github.com/akserg/ng2-dnd#demo) section of README with links.

**Comment by Abrissirba** [comment]
Hi

Sorry for not being able to fully describe my intent :)

I want to setup an environment so that I can correct bugs in the source code of the project. I don't see how I can do that from reading the Demo section. What I could do I guess, is to copy the TypeScript files in the src folder into a new "demo-development" project and change the TypeScript code there and then copy that code back into this project. 

How are you developing this project. Du you only run unit tests with no graphical view where you can try the drag n drop yourself?

**Comment by akserg** [comment]
Ah, I get you point now.

I can suggest the following steps:
1. for the module
- Fork this project into your repo
- Pull it into the local folder on Mac, Linux, etc.
- Run `npm install`
- Use `npm link` in the local folder to create a symlink from local package to the global one. More about that [here](https://docs.npmjs.com/cli/link)

2. for demo
- Pull one of the demo projects. Take [webpack](ng2-webpack-demo), for example.
- Run `npm install`
- Run `npm link ng2-dnd` to create a symlink from globally-installed package-name to `node_modules/` of the current folder
- Run `npm start` and open the browser
- Make changes in the module and see how it builds and reloads in the browser

3. afterwords
- Fix or improve the module's code
- Update or create tests. Be sure all pass with success or it will fail on CI build (on Travis)
- Push changes to your repo
- Create pull request to this one
