### ISSUE TITLE
dnd-sortable-handle breaks the sorting

### ISSUE THREAD

**Issue by ruant** [akserg/ng2-dnd#150]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Is it just me or does `dnd-sortable-handle` break the sorting?
Copied the simple sorting example, that works fine at start. When adding the dnd-sortable-handle to a <span> then nothing works.

* **What is the current behavior?**
Breaks the sorting.

* **What is the expected behavior?**
That the element can be moved, and moved only with through using the `dnd-sortable-handle` marked element.

- Angular version: 4.1.2
- Browser: Only tested in Chrome

**Comment by iignatov** [comment]
This one looks like a duplicate of #144.

**Comment by ruant** [comment]
@iignatov Thanks for the heads up. I'll close this.
