### ISSUE TITLE
possible to show a border on target droppables?

### ISSUE THREAD

**Issue by seiyria** [akserg/ng2-dnd#155]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
feature, if doesn't exist.

* **What is the current behavior?**
Based on the [demo](http://akserg.github.io/ng2-webpack-demo/#/dnd) there is no indication of where you can drop besides the title. 

* **What is the expected behavior?**
I'd like to see a border around the target elements that are valid drop zones, before hovering over them.

* **What is the motivation / use case for changing the behavior?**
Usability would go up in the case where what items can be dragged into what containers is obvious.

You can see an example of this being done [here](http://plnkr.co/edit/2bjGgzWnbFrciEiCKLew?p=preview).

**Comment by akserg** [comment]
Hi @seiyria 

The `ng2-dnd` supports that feature via styles you can change for your own project:
```
.dnd-drag-start {
    -moz-transform:scale(0.8);
    -webkit-transform:scale(0.8);
    transform:scale(0.8);
    opacity:0.7;
    border: 2px dashed #000;
}

.dnd-drag-enter {
    opacity:0.7;
    border: 2px dashed #000;
}

.dnd-drag-over {
    border: 2px dashed #000;
}

.dnd-sortable-drag {
  -moz-transform:scale(0.9);
  -webkit-transform:scale(0.9);
  transform:scale(0.9);
  opacity:0.7;
  border: 1px dashed #000;
}
```
You can find them inside the `style.css` available as a part of `ng2-dnd`. Just include them into you project as described in README file. You may find an example of the usage [here](http://embed.plnkr.co/JbG8Si).
