### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ferredel** [akserg/ng2-dnd#16]
Demo at http://akserg.github.io/ng2-webpack-demo/#/dnd is not working for me :(

With Chrome 49

**Comment by akserg** [comment]
Log from console, please.

**Comment by ferredel** [comment]
@akserg 

For more info: I can drag the items, but I when I drop them  on the target zone nothing happens...
 ```
service.ts:99TypeError: Cannot read property 'next' of undefined(…)
service.ts:100!!! Suggestion: Seems you forget add <ng2-slim-loading-bar></ng2-slim-loading-bar> into your html?
lang.ts:404Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode. 
```

**Comment by akserg** [comment]
I use Chrome 50 on Mac:
![image](https://cloud.githubusercontent.com/assets/1400409/14935493/d25f7d54-0ed3-11e6-8c3d-a9edce3c1c3a.png)
and all work fine.

Bear in mind the fact that first two topics on example page do not show any feedback about the drop event:

- `Simple Drag-and-Drop`
- `Restricted Drag-and-Drop with zones.' 

Try the `Transfer custom data in Drag-and-Drop` and following topics, and let me know if they are not working for you?

**Comment by ferredel** [comment]
Updated to chrome 50 (on Debian jessie )  and now it works.

Weird thing, with Chrome 49, it dosen't work at all, not `Transfer custom data in Drag-and-Drop` neither `Drag-and-Drop - Shopping basket`

**Comment by akserg** [comment]
Yep.
Look at the following link [Drag and Drop on Google Drive Not working with Chrome Browser](https://productforums.google.com/forum/#!topic/drive/V0Eh3VgaOCM). Seems that was a bug in Chrome 49. 👎
