### ISSUE TITLE
How does the scroll-on-drag work?

### ISSUE THREAD

**Issue by paw1** [akserg/ng2-dnd#160]
I'm trying to implement both dragula and dnd in a page. While the scroll on drag is working with dnd elements, the same is not working for dragula elements. How does it work?

**Comment by malchijah** [comment]
Hi @paw1 did it work for you? If so how did you fix it?

**Comment by paw1** [comment]
[dom-autoscroller](https://www.npmjs.com/package/dom-autoscroller)
