### ISSUE TITLE
No support for  changeDetection: ChangeDetectionStrategy.OnPush,

### ISSUE THREAD

**Issue by chpoit** [akserg/ng2-dnd#167]
* **I'm submitting a ...**
[ X ] bug report
[ X ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
This is both a feature request and a bug report.

* **What is the current behavior?**
In order to avoid pointless view refreshes, I use changeDetection: ChangeDetectionStrategy.OnPush for most of my components. However, when you have a "dnd-sortable-container" with OnPush detection, the view isn't updated as changing the order of items within an array isn't an event. 

**EDIT:**
Upon further investigation it would appear that markForCheck is being called, but not in the main _onDragEnterCallback method, making it so that the changeDetector isn't being notified.

Without OnPush, the view and ordering of items is updated just fine.

* ** Reproduction:

Simply import     ChangeDetectionStrategy from @angular/core and add "changeDetection: ChangeDetectionStrategy.OnPush" to a component declaration that has a sortable container within.

* **What is the expected behavior?**

It would be nice that what changes the array contents would call ChangeDetectorRef.markForCheck() whenever the contents are change.

* **What is the motivation / use case for changing the behavior?**
Right now I have to create an interval that calls ChangeDetectorRef.markForCheck() whenever the drag starts and kill it when it ends

* **Please tell us about your environment:**

- Angular version: 4.2.X
- Browser: all

**Comment by mawo87** [comment]
@chpoit I do have the same problem. Due to performance reasons I switched my change dection strategy to OnPush for my components. Now, as you mentioned, the sortable behavior seems to be broken. Can you post an example (snippet/plunkr) how you solved the issue on your end?

**Comment by chpoit** [comment]
@mawo87 I didn't. I created a quick pull request (#168)  that adds a call to markforcheck, but only for sortables a while ago, but it hasn't been merged yet. Ideally I should go and completely convert ng2-dnd to OnPush, but I don't have the time while I'm at work to do so.

 If I don't want a clunky movement I create an interval on a 100-300ms using the onDragStart event and dismiss the interval with the onDragEnd event. This feels gross, but it works and is simpler than creating a forked npm package.

**Comment by mawo87** [comment]
Thanks for the note - sounds like a solid workaround.
