### ISSUE TITLE
No obvious way of retrieving the drop coordinates

### ISSUE THREAD

**Issue by jimitndiaye** [akserg/ng2-dnd#17]
There doesn't seem to be a way of retrieving the coordinates of the dropped item.

**Comment by jimitndiaye** [comment]
Maybe change the payload of the drop/drag events to include the native event as well as the custom data (if any) in separate properties. Sometimes it is important to know exactly where in the destination component the item has been dropped.

**Comment by akserg** [comment]
Sorry, very busy today and tomorrow. I can answer your question only on Thursday.

**Comment by akserg** [comment]
Available from v 1.6.3
