### ISSUE TITLE
change libraries to @angular/core, etc

### ISSUE THREAD

**Issue by bdsimpson** [akserg/ng2-dnd#18]
The package.json file correctly requires @angular modules as dependencies for 2.0.0-rc.1.

However, the individual files, like dnd.service.ts still import from 
angular2/core
angular2/src/facade/lang

I believe that they should be importing from @angular

**Comment by akserg** [comment]
Hi,

I'm very busy today. I will migrate the code of package tomorrow.

Sorry for delay.

**Comment by Dimanoid** [comment]
Any chance of tomorrow come soon? :)

**Comment by akserg** [comment]
:)

**Comment by akserg** [comment]
Available in v 1.6.1
