### ISSUE TITLE
Suggestion: Move `@angular/*` from devDependencies to `peerDependencies`

### ISSUE THREAD

**Issue by leocaseiro** [akserg/ng2-dnd#202]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature/improvement

* **What is the current behavior?**
Currently, we're installing multiple versions of angular (when testing with angular 5).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

* **What is the expected behavior?**
We should rely on the `@angular/*` versions installed in the app.
However, we could and should leave the `@angular/cli`, `@angular/compiler`, `@angular/compiler-cli`,  and `@angular/language-service` in devDependencies still.

* **What is the motivation / use case for changing the behavior?**
be able to test any `@angular@next` avoiding conflict issues, such as
> `ERROR in Error: Metadata version mismatch for module`

* **Please tell us about your environment:**
```
@angular/cli: 1.4.4
node: 8.6.0
os: darwin x64
@angular/animations: 5.0.0-rc.0
@angular/cdk: 2.0.0-beta.11
@angular/common: 5.0.0-rc.0
@angular/compiler: 5.0.0-rc.0
@angular/core: 5.0.0-rc.0
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 5.0.0-rc.0
@angular/http: 5.0.0-rc.0
@angular/material: 2.0.0-beta.11
@angular/platform-browser: 5.0.0-rc.0
@angular/platform-browser-dynamic: 5.0.0-rc.0
@angular/router: 5.0.0-rc.0
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.5.3
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

**Comment by akserg** [comment]
Implemented in 5.0.1
