### ISSUE TITLE
not working in angular2 rc1

### ISSUE THREAD

**Issue by Bhushan001** [akserg/ng2-dnd#21]
I was trying this demo.but when I am trying to import ng2-dnd module its giving me errors.Also systemjs configuration is not updated according to angular2 rc1. if anyoneone could help .it will be great

**Comment by akserg** [comment]
Hi Bhushan,

I didn't update demo yet, but will fix it on the week end.

**Comment by akserg** [comment]
I have updated SystemJS [demo](https://github.com/akserg/ng2-systemjs-demo).
Webpack will coming soon.
