### ISSUE TITLE
Cannot drag items into empty (dnd-sortable-container) that initialized with items

### ISSUE THREAD

**Issue by jrhorrisberger** [akserg/ng2-dnd#24]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  Bug
- **What is the current behavior?**
  If you drag all dnd-sortable from a dnd-sortable-container (thus emptying it) you can no longer drag items back into this dnd-sortable-container. If the dnd-sortable-container initialized as empty, it works as expected
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
  On the Demo site [http://akserg.github.io/ng2-webpack-demo/#/dnd](http://akserg.github.io/ng2-webpack-demo/#/dnd) either, "_Multi list sortable"_ or _"Simple sortable With Drop into something, without delete it"_ example. -- In the case of "Multi list sortable"     **1.** Drag all items from "Available boxers" into other containers (First or Second Team),    **2.** Then try to drag these items back to "Available boxers." **Notice:** First/Second team (which initialized empty) work as expected.
- **What is the expected behavior?**
  Items should be able to be dragged back into (empty) containers that initialized with items.
- **What is the motivation / use case for changing the behavior?**
  NA
- **Please tell us about your environment:**
  Bug is apparent even in Demo site
- **Angular version**: _2.0.0-rc.2_, using Angular-CLI
- **Browser:** **Chrome:**_51.0.2704.79_ **Firefox:**_48.0a2 (2016-06-01)_ **IE:**_11.306.10586_
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
  NA

**Comment by psolidgold** [comment]
Confirming this issue is happening for me as well.

**Comment by JuanDaniel1995** [comment]
It is happening to me as well.

**Comment by j040p3d20** [comment]
I had the same problem and my controller was assigning new arrays into the sortableData variables, instead of adding/removing elements.

i changed the manipulation of those arrays from

this.fields = response;

to

this.fields.push(...response);

and it worked correctly. I guess the dnd directive is watching the objects assigned to those variables and when we assign a new object instead of manipulating the data inside the current object, the directive is no longer able to monitor changes in the new array.

**Comment by akserg** [comment]
Thanks @j040p3d20 
I will have a look.

**Comment by gagechoat** [comment]
Happening for me, too, when I splice the array down to zero items.

**Comment by rmcsharry** [comment]
I can confirm this also, but I have a rather clever workaround....not hard to implement, just 10 minutes work:

1. In your template create two identical containers: one empty, and one with your initial list, let's call them 'fake' and 'real'
2. On the fake one: 
`*ngIf="real.contents.length == 0"`
3. On the real one:
`*ngIf="real.contents.length > 0"`

Note they are both checking the length of your bound array (`contents`), containing your initial list. The 'fake' container is not bound to anything, it's just a dropzone that fires the drop event.

When your component initialises the rule in (3) will fire and you will see your real container, with its bound elements. If the user removes them all, rule (2) will fire and they will now see the fake container (which is empty). Rule (3) will also fire removing your now broken real container from the DOM. Hence the user cannot try to drop into it any longer, instead they will drop their next item into the fake container (which looks identical).

So now when the user drops something on this fake container, you push it into 'contents' array, which will then case both rules fire: (3) to show your real container and rule (2) to remove your fake container from the DOM.

**Comment by norenma** [comment]
@rmcsharry That worked for me. Many thanks!
