### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ppacher** [akserg/ng2-dnd#274]
Hi, I'm wondering if this project is still maintained? There are a couple of major bugs (like memory leak in SortableComponent) and a bunch of issues. Most of them have been reported months/years ago and it seems like they are not getting fixed. Moreover, there still no support for Angular 6 (and Angular 7 is on it's way and will be released quite soon).

Best regards,
Patrick

**Comment by BBenQi** [comment]
It doesn't seem to be maintained

**Comment by tosehee75** [comment]
Don't you hate the open source that isn't maintained?

**Comment by ppacher** [comment]
I think it's normal that open source projects are stopped being maintained. Although I think it should be mentioned on the README (i.e. Use on your own risk, there will be no bugfixes). However, (no directly meaning this project), I hate "open source projects" that are published to NPM/Pip/... without ever thinking about maintenance. If it's just used for a local project and is not meant to be bugfixed/improved it should definitely not be published to package managers. If I really want to use such a project, cloning it and linking it to my own one will not be a deal-killer.

**Comment by jessycormier** [comment]
It would also be important for those using the open source project to be apart of it so it continues to grow, adapt, and change. If someone out there (like us) where to take over the project and continue it's development that would be great. right @tosehee75 ;)   

@ppacher the next version of angular that is being worked on will have a built in solution for drag and drop within the material design project. I believe it'll be part of the CDK, and you can opt to only use that part of the CDK :) check this link once angular 7 is released: https://material.angular.io/cdk/categories/component-composition
