### ISSUE TITLE
Update to angular 7

### ISSUE THREAD

**Issue by richardlnnr** [akserg/ng2-dnd#278]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
The Angular version in the project is 5.0.0

* **What is the expected behavior?**
Update to the latest version of Angular

* **What is the motivation / use case for changing the behavior?**
My project use this implementation and the Angular Material Drag and Drop don't works for me.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I can made this. Just I need permission on project.

**Comment by PhiLhoSoft** [comment]
> I can made this. Just I need permission on project.

Perhaps you can make a fork, otherwise? It would be useful to lot of people, I bet.

**Comment by richardlnnr** [comment]
I make a fork for update the project, thanks
