### ISSUE TITLE
How to use bundled ng2-dnd.js?

### ISSUE THREAD

**Issue by martinsik** [akserg/ng2-dnd#28]
* **I'm submitting a ...**
[  ] bug report
[  ] feature request
[x] question about the decisions made in the repository

* **What is the current behavior?**
SystemJS isn't able to find registered modules from the bundle.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.
See https://github.com/martinsik/ng2-systemjs-demo

* **What is the expected behavior?**
Loading just `ng2-dnd.js` bundle should be enough to import `ng2-dnd/ng2-dnd`.

* **What is the motivation / use case for changing the behavior?**
I'm trying to figure out how to use the bundled version of `ng2-dnd`. I'd expect that I can just add `bundle` option to `systemjs.config.js`. I tried to update the `ng2-systemjs-demo` demo https://github.com/martinsik/ng2-systemjs-demo and switch from using the unpacked `ng2-dnd` from `node_modules` to bundled `ng2-dnd.js`.
I'm supposed to import `ng2-dnd/ng2-dnd` but the main module is registered to SystemJS as `ng2-dnd` (see [line 743](https://github.com/akserg/ng2-dnd/blob/master/bundles/ng2-dnd.js#L743)) so I don't think it's able to load it properly (even though the js file is found and loaded propertly).
Another thing is that one of the modules defines as its dependency `@angular/common/src/facade/lang` ([line 519](https://github.com/akserg/ng2-dnd/blob/master/bundles/ng2-dnd.js#L519)) which is not exposed by the bundled [`common.umd.js`](https://npmcdn.com/@angular/common@2.0.0-rc.1/common.umd.js) package so even if I change module names in `ng2-dnd.js` manualy it throws an error because it's not able to load `@angular/common/src/facade/lang`. The original ng2-systemjs-demo works because it loads angular2 modules from `node_modules`.

   At the end I was able to run in with two modifications:
   - prepend `ng2-dnd` to all module names (eg: `ng2-dnd/src/dnd.sortable` or `ng2-dnd/ng2-dnd` for the main module).
   - remove  `@angular/common/src/facade/lang` dependency and `isPresent` function.  

   Then add `bundle` option to SystemJS config:

   ```
    var config = {
        bundles: {
            '/path-to-bundles/ng2-dnd.js': ['ng2-dnd/ng2-dnd'],
        }
    }
```

   and it works. Maybe I'm just stupid and I could solve all this with SystemJS config but I tried to follow the same structure as generated by [`ng2-file-upload`](https://github.com/valor-software/ng2-file-upload) package which seems to me very understandable.

- Angular version: 2.0.0-rc.1
- Browser: all

**Comment by akserg** [comment]
Hi Martin,

Thank you for usage of this library. I think the best solution here is use lodash library with isPresent function rather than Lang module. What do you think about it?

**Comment by dancancro** [comment]
I am using the library with an angular-cli project and wanted to share what I learned. It might help someone in the same situation. 

In addition to the other setup instructions, modify your angular-cli-build.js file to look like the following. This will cause the appropriate files for the library to be copied into the dist/ directory during the build step of `ng serve`, so re-run `ng serve` after making the change:
```
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
      'ng2-dnd/ng2-dnd.js',
      'ng2-dnd/src/dnd.service.js',
      'ng2-dnd/src/dnd.draggable.js',
      'ng2-dnd/src/dnd.droppable.js',
      'ng2-dnd/src/dnd.sortable.js',
      'ng2-dnd/src/dnd.component.js',
      'ng2-dnd/src/dnd.config.js'
    ]
  });
};

```

This is the solution that worked for me. Let me know if there is a better way.

Also, @akserg, I have  two questions:
1) What is the preferred way to ask new questions about this library?
2) Is it possible to have a draggable item in which only a part of it serves as the drag handle and the rest of the text can be selected like regular text? [This](https://github.com/RubaXa/Sortable) other project provides that but it is not implemented in Angular 2.

**Comment by martinsik** [comment]
Hey Akserg,
I did some search myself last week and I think there're generally two ways of generating bundles using SystemJS Builder in a way that it creates correct module paths.

- #### The first is what [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) uses:  
They set baseURL to `..` and then to running the builder they use: builder.bundle('ng2-file-upload/ng2-file-upload'). The first `ng2-file-upload` stands of directory name of the entire repository, the second `ng2-file-upload` is in fact `ng2-file-upload.js` file (they use also `paths: { '*': '*.js' }`).   
This makes all module names prefixed with `ng2-file-upload` because they're all in a directory called `ng2-file-upload` and the main module that you import is `ng2-file-upload/ng2-file-upload` because it matches `ng2-file-upload/ng2-file-upload.js` file.  
**Pros:**
  - It's very easy to setup. In particular for `ng2-dnd` this could mean just setting `baseURL: '..'` in `make.js`.  
  - All paths will be prefixed with `ng2-dnd`. It looks like the SystemJS will override duplicate definitions so if there were two modules registered as `src/translate.parser` it'll override the original and most likely break. [ng2-translate](https://github.com/ocombe/ng2-translate) ignores this which is in my opinion a bad practice.

  **Cons:**
  - Generated path structure is dependent on your directory structure.
  - The end user has to import `ng2-file-upload/ng2-file-upload` which looks weird and it's not obvious why we can't use just `ng2-file-upload`. In fact you could compile TypeScript with importing just `ng2-file-upload` because it's able to find `ng2-file-upload.d.ts` thanks to `typings` parameter in `package.json` but then it won't be able to load properly because of relative paths in the bundled JavaScript.

- #### The second is what I'm using right now in [ms-treeview](https://github.com/martinsik/ms-treeview/blob/master/bundles/ms-treeview.js) but it's very similar to what you and [ng2-translate](https://github.com/ocombe/ng2-translate) use:  
 My [`ms-treeview`](https://github.com/martinsik/ms-treeview) repository contains top level directory `ms-treeview` that serves as prefix for all modules. Then bundling: `builder.bundle('ms-treeview')` creates main module as `ms-treeview` because of `ms-treeview.js` and [all other modules are prefixed with `ms-treeview`](https://github.com/martinsik/ms-treeview/blob/master/bundles/ms-treeview.js) because they're in `ms-treeview` subdirectory.
 **Pros:**
 - All paths are prefixed
 - End user will import just `ng2-dnd` (compilation will work thanks to `typings` parameter in `package.json`).

 **Cons**:
 - Having a top level directory in my repository named the same as the repository looks weird.

I'd personally recommend using the fist option because it won't break backward compatibility for people using this library already and only affect the bundle JavaScript code.

Another thing to consider is ignoring all `*.ts` files in [`.npmignore`](https://github.com/valor-software/ng2-file-upload/blob/development/.npmignore). This is important because when compiling a TypeScript application the compiler prefers `.ts` in favor of `*.d.ts` so the generated output will create dependencies to `node_modules` which is what you never want. [`ng2-file-upload`](https://github.com/valor-software/ng2-file-upload/blob/development/.npmignore) does this the right way.

Regarding `@angular/common/src/facade/lang`, I'd recommend to remove this dependency completely, without using `lodash`. I'm not sure what `isPresent` does exactly but it's used only twice so even checking with typeof(value) === 'undefined' would be ok I think (this is probably not even necessary in TypeScript).
