### ISSUE TITLE
Not able to add dropZones

### ISSUE THREAD

**Issue by mburger81** [akserg/ng2-dnd#3]
I'm using angular webpack starter with angular2 beta.9 and ng2-dnd 1.0.4 and have this html

```
<div>
    <h2>Menu</h2>
    <ul id="menu">
      <li dnd-droppable [dropZones]="['xxx']">Menu1</li>
      <li dnd-droppable [dropZones]="['yyy']">Menu2</li>
      <li dnd-droppable [dropZones]="['yyy']">Menu3</li>
    </ul>
  <div>
  <br><br>
  <div id="dashboard">
    <h2>Dashboard</h2>
    <div id="container" class="containerX" dnd-draggable [dragEnabled]="true">
      <p>Container1:</p>
      <div id="widgets">
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['xxx']">Widget 1</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['xxx']">Widget 2</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['xxx']">Widget 3</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['xxx']">Widget 4</div>
      </div>
    </div>

    <div id="container" class="containerX" dnd-draggable [dragEnabled]="true">
      <p>Container2:</p>
      <div id="widgets">
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['yyy']">Widget 5</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['yyy']">Widget 6</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['yyy']">Widget 7</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['yyy']">Widget 8</div>
      </div>
    </div>

    <div id="container" class="containerX" dnd-draggable [dragEnabled]="true">
      <p>Container3:</p>
      <div id="widgets">
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['xxx']">Widget 9</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['xxx']">Widget 10</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['xxx']">Widget 11</div>
        <div class="widgetX" dnd-draggable [dragEnabled]="true" [dropZones]="['xxx']">Widget 12</div>
      </div>
    </div>
  </div>
```
I would like to drag the widgets into the sub menus, in my case the widget from container1 and 3 into Menu1.
But in some way the declaration of [dropZones] in dnd-draggable seam to not work

in `private _isDropAllowed(): boolean {` in dnd.droppable.ts the value for `this._dragDropService.allowedDropZones.length` is always 0

I'm doing something wrong?

**Comment by mburger81** [comment]
I saw
```
private _onDragStart(event: Event): void {
        console.log('ABC: ', event, this.dragEnabled, this.dropZones);
        if (this.dragEnabled) {
            this._dragDropService.allowedDropZones = this.dropZones;
            this._onDragStartCallback(event);
        }
    }
```

will be called two times, first time `this.dropZones` has the right values and the second time it is an empty array?

**Comment by mburger81** [comment]
@akserg okay I found the problem.

The problem is, I have one dnd-draggable per container and then always four dnd-draggable for each widget into the container.
I have to drag the whole container or some widget from the container.
In this case the onDragEvent will call first for the widget with the declared dropZones and then for the whole container which hasn't declared dropZones!

So how can I handle this use case?

**Comment by akserg** [comment]
I have created plunker you can use for testing you application: http://embed.plnkr.co/yYk2hU/
Can you fork my planker and update it accordingly with you code, so I will explore it to find the issues you met. It would be nice if you will briefly explain what you trying to develop.

**Comment by mburger81** [comment]
@akserg  okay thx, I will do it tomorrow, for today I have to do some other things.

do you think you can add also the functionality a drag&drop like switch positions for containers? Your lib does the wor for dragging into anything using html5 dragging function.

But I need also to drag DIVS (containert) for switching their positions.

I will share tomorrow your forked plnkt with my updates.

**Comment by mburger81** [comment]
Hi,

here is my forked and changed plnkr example
http://plnkr.co/edit/ltolE7?p=preview


In this example Container1 until Container2 and Widget1 until Widget 12 al
are draggable, and here it works fine. I'm able to drag al widget also if
 they are a child of container which is also draggable. In my app this is
not working, I will give a look to it.

The thing I want to do now is, al Containers a droppable into Menu1, Menu2,
Menu3 as the Widget1-10 can do!
But the f more I want to do with the Containers is, to change there
position. so Container 1 i want to drag after Container 3 and so on. This
is a normal DESKTOP - ICON drag and drop behavior, with your lib we can
drop a element into a other one, and that is great. It's better working
then every other lib i tried. But I also need the possibility to drag a
Container before or after an other one, so this is nit a DROP operation but
a drag and change position, many other libs do this. That's the thing I
need to simulate my DESKTOP in the browser =)

what do you think

thx
Michael



2016-03-20 20:27 GMT+01:00 Sergey Akopkokhyants <notifications@github.com>:

**Comment by akserg** [comment]
I;m busy implementing 'sortable' Drag-and-drop components. Need to finish with unittests and I planning to issue the new release tomorrow.

**Comment by mburger81** [comment]
@akserg that's great to hear, the cortable Drag-and-drop thing is that what I needed!! GREAT

thx

**Comment by mburger81** [comment]
@akserg
I'm sorry to stress you, really sorry! We kicked off dragula today and we are waiting for your sortable function.

Another question, is it possible to emit the events "dragStart" "dragEnd" and "dragCancelld"???

thx
Michael

**Comment by akserg** [comment]
Ah, you don't stress me. 
I realized my solution didn't accept sortable one and I decided to redesign and recreate it completely, and this is why it takes to long, but now all sorted, I'm busy with final unit tests for sortable, update demo, plunker and I'm are done.

**Comment by akserg** [comment]
Yes, I will add emitters for those events at the end, so will unit tests them as well.

**Comment by mburger81** [comment]
Okay thx, on friday I have a presentation and if I can implement this until
there It will really thankfull
Am 23.03.2016 6:31 nachm. schrieb "Sergey Akopkokhyants" <
notifications@github.com>:

**Comment by akserg** [comment]
Ok. 
Beer from you. :)

**Comment by akserg** [comment]
Finally, ng2-dnd version 1.1.0 available over NPM registry. You may find examples in references projects. Web pack is not work for now - I need have a look. Check this plunker to see it in action: http://plnkr.co/edit/yFdvPT?p=info

**Comment by mburger81** [comment]
Thx I will try it tomorrow morning, great!

There are several problems on latest angular2 webpack starter, which I
discussed last days on github.

I spent 2 days to get it work again. If I can help you, you are welcome!
Am 23.03.2016 10:46 nachm. schrieb "Sergey Akopkokhyants" <
notifications@github.com>:

**Comment by akserg** [comment]
It would be nice to know how did you fix the issues with webpack.

**Comment by mburger81** [comment]
It depends I had many problems, what are your problems?

2016-03-24 4:06 GMT+01:00 Sergey Akopkokhyants <notifications@github.com>:

> It would be nice to know how did you fix the issues with webpack.
>

**Comment by akserg** [comment]
Sorted.
