### ISSUE TITLE
Display a tool-tip before dropping an element

### ISSUE THREAD

**Issue by Bhushan001** [akserg/ng2-dnd#34]
- **I'm submitting a ...**
  [ ] feature request that whenever I am dropping an item on any element , I should get a tooltip message "Drop Here".
- **What is the expected behavior?**
  I am dragging and dropping components from component-list and I am able to drop them in certain area.what I am willing to do next is when I am dropping content over certain region that area should display a tool-tip "Drop Here" .
- **Please tell us about your environment:**
  I am using angular2-rc1 with angular-cli.
- Angular version: 2.0.0-rc.1
- Browser: [Chrome ]

any inputs on this?

**Comment by Bhushan001** [comment]
@akserg any inputs on this?

**Comment by akserg** [comment]
Hi @Bhushan001,

Sorry, enormously busy. Will have chance to look at your and other issues only after 20 of October.

**Comment by Bhushan001** [comment]
@akserg thanks for quick response..no problem.. any idea on how it can be done.. so I will try this meanwhile.. and raise a pull request?

**Comment by akserg** [comment]
What the kind of tooltip would like to display? Do you use especial library to show them or you are expecting that the code of ng2-dnd will do that?

**Comment by Bhushan001** [comment]
I am expecting ng2-dnd to show that... Perhaps setting tooltip where droppable is  mentioned : 
Also It should allow specific Types to be dropped.

Something like this:

       `<div dnd-droppable dnd-tooltip="Drop Row Here" drop-type-allowed="ROW" class="panel panel-warning">
            <div class="panel-heading">Restricted to drop</div>
            <div class="panel-body">
                <div dnd-droppable dnd-tooltip="Drop Component Here" drop-type-allowed="COMPONENT"></div>
            </div>
        </div>`

is this possible...?

if yes, what approach should I take?

I will implement this & revert you on this.

**Comment by akserg** [comment]
Hi, @Bhushan001,

Please reopen if that issue still actual for you.
