### ISSUE TITLE
Weird behaviour when container becomes empty 

### ISSUE THREAD

**Issue by kunjee17** [akserg/ng2-dnd#38]
I'm facing weird behaviour for droppable container. When I drop all the items from one container to another, means I emptied first container. After this I'm unable to add back items from second container to first one, the empty one. I'm unable to do so. 

Am I missing something? Or it is default behaviour?

**Comment by akserg** [comment]
No, that's an issue. I need to fix it.

**Comment by SarojiOS** [comment]
Hi,
I am also facing the same issue. is it fixed in the latest update?

**Comment by Bhushan001** [comment]
@akserg Hi , is there any fix for this issue?

**Comment by akserg** [comment]
Hi 

That issue was fixed quite a while ago. Please use the latest release.
