### ISSUE TITLE
counter intuitive bahaviour when dropping a sortable outside the list

### ISSUE THREAD

**Issue by zuloo** [akserg/ng2-dnd#39]
When pulling a sortable outside the list (drop zone) and releasing it (dragend event, not dragsuccess)
the browser animates the dragged item back to its original position while it stays in the last acquired sorted position in the list.

example

----------------(upper bound)
1
2
3
4
----------------(lower bound)

drop here outside sortable-container

dragging the "2" across the lower bound and dropping it there causes an animation in the browser, that guides the "2" back to its original position behind the 1, while the list is reordered as follows:

1
3
4
2

that confuses me, and I have the feeling that the sorting should only be applied when dragsuccess event is emitted, or at least there should be some means to choose between the two behaviors (with some directive for example).

**Comment by akserg** [comment]
Hi, @zuloo 

Because you are using sortable container and dragging the element over other elements, the container moves the host element into the last position - that is right behavior. 

I don't know how to help you.

Please reopen if this issue still actual for you.

**Comment by zuloo** [comment]
How can you say it is right behavior, when there is no drag-success event released, does that not imply, that the drag was unsuccessful and thereby should not have an influence on the order of the elements?
IMHO only successful drag operations should lead to rearranging the list.
I do not expect an answer from you, as it took you over 1 year to come up with this one - you do not seem to be interested in good UX Design..

**Comment by akserg** [comment]
I would like to see your PR next as fix of my bad UX Design.

**Comment by zuloo** [comment]
I use my own dnd-implementation by now, maybe 1 year in the past, that could have been an option...
