### ISSUE TITLE
Examples not working in Safari 9.0.3

### ISSUE THREAD

**Issue by peterklima** [akserg/ng2-dnd#4]
Hi!

Unfortunately the official examples are not working in Safari 9.0.3. (Not able to drop anything in the drop target)
Also the http://embed.plnkr.co/yYk2hU/ is not working.

KR Peter

**Comment by akserg** [comment]
I will have a look today.

**Comment by akserg** [comment]
Need to check what is wrong on Safari from http://www.html5rocks.com/en/tutorials/dnd/basics

**Comment by workfluo** [comment]
Hello, have you found a solution for this Safari pb?

**Comment by akserg** [comment]
Fixed in release 1.4.1
Tested in official [demo](http://akserg.github.io/ng2-webpack-demo/#/dnd).
Please test and reopen if this issue was not fixed in your application as well.
