### ISSUE TITLE
Modify the item being dragged

### ISSUE THREAD

**Issue by Brocco** [akserg/ng2-dnd#40]
I apologize in advance for skipping the template as it did not seem to accommodate asking a question.

Is there a way to get a handle (CSS selector) to the item being dragged?

I would like to add some additional styles to the item being dragged and have not been able to determine the best course of action. I'd prefer to not use `dragImage` as I **love** the idea of showing dynamic content on the item being dragged.

If that does exist then I guess I'm suggesting a feature of adding a class `dnd-drag-item` to the DOM element being dragged.

**Comment by DzmVasileusky** [comment]
@Brocco 
Can you provide an example of using cloneItem setting?
Where should I switch it on?
