### ISSUE TITLE
Multiple Drag and Drop Feature

### ISSUE THREAD

**Issue by poonsv** [akserg/ng2-dnd#43]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository

Will multiple Drag & Drop from 1 container to a drop zone be on the roadmap?
- **What is the current behavior?**
  Is it not supported.
- **What is the motivation / use case for changing the behavior?**
  We have a number of requirement that need to select multiple items in one container and drag them to a drop zone all at the same tine,
- **Please tell us about your environment:**
  Angular2 RC4/ Net Core
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  all

**Comment by hgoraya** [comment]
just want to confirm when we can have multiple drag drop working

**Comment by akserg** [comment]
Hi @hgoraya 
I don't have time to implement this feature just now because of the short amount of time on this project.
