### ISSUE TITLE
How to pass multiple data in dragData while dragging ?

### ISSUE THREAD

**Issue by Bhushan001** [akserg/ng2-dnd#44]
I want to know whether it is possible to pass multiple arguments in dragData ? 
For eg.

I want to drag a component from multiple locations so I tried doing something like this.
`[dragData]="aComponent,'component-in-bar'"`
`[dragData]="aComponent,'component-in-designer'"`

so When I am catching the event , I could do something like this:
`dnd-droppable (onDropSuccess)="loadComponent($event)"`

`loadComponent($event){
        console.log($event.dragData.aComponent);
        console.log($event.dragData.location); //  'component-in-bar OR component-in-designer
}`

**Comment by AlexisFinn** [comment]
1) As an array: `[dragData]="[aComponent,'component-in-bar']"`
2) As an object: `[dragData]="{component: aComponent, type: 'component-in-bar'}"`

**Comment by akserg** [comment]
Thank you @AlexisFinn
