### ISSUE TITLE
Angular RC5

### ISSUE THREAD

**Issue by daniele-zurico** [akserg/ng2-dnd#54]
* **I'm submitting a ...**
[x] bug report

* **Do you want to request a *feature* or report a *bug*?**
Is possible to have dnd working for angular rc5?
Actually it doesn't work if you put the drag in one module and the drop in another one.

Example:
@NgModule({
    imports: [
      PageManagerModule
   ],
declarations: [
Charts,
DND_DIRECTIVES
]

Charts contains the drag and PageManager contain the drop.
I'm able to drag but not able to drop.

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by daniele-zurico** [comment]
Someone found a work around to have that one working in RC5?

**Comment by marcosbeto** [comment]
Anyone?

**Comment by magiccrafter** [comment]
Check this: https://github.com/akserg/ng2-dnd/issues/57

**Comment by akserg** [comment]
Fixed in 2.0.0
