### ISSUE TITLE
The bug: The 'dnd-sortable-container' shows 'move' cursor

### ISSUE THREAD

**Issue by akserg** [akserg/ng2-dnd#6]
The 'dnd-sortable-container' must not show 'move' cursor when mouse overhead the host element of it.

**Comment by akserg** [comment]
Sorted.

**Comment by crh225** [comment]
@akserg, this appears to be an issue still in you demo
http://akserg.github.io/ng2-webpack-demo/#/dnd

**Comment by crh225** [comment]
this still appears to be an issue in 
**Simple sortable With Drop into something, without delete it**
http://akserg.github.io/ng2-webpack-demo/#/dnd

**Comment by papuche** [comment]
Will you work on this ?
