### ISSUE TITLE
Update code structure to export an NgModule

### ISSUE THREAD

**Issue by Brocco** [akserg/ng2-dnd#61]
* **I'm submitting a ...**
[ ] bug report
[ X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Exporting provides and directives

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

* **What is the expected behavior?**
Allow the package to export a class as an NgModule for consumption in applications

* **What is the motivation / use case for changing the behavior?**
As of RC6 the bootstrap process is focused on structuring libraries as NgModules.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Brocco** [comment]
If this is something you'd like me to work on (I might anyway) please let me know!

**Comment by Brocco** [comment]
FYI, I have started working on this here: https://github.com/Brocco/ng2-dnd/tree/ng-upgrade

and have been getting this error when importing it into my application:
`metadata_resolver.js:230Uncaught Error: Unexpected value 'DndModule' imported by the module 'AppModule'`

**Comment by akserg** [comment]
Please latest 2.0.0 and confirm that issue still exists.

**Comment by Gillardo** [comment]
Any news when this is going to be released and published to npm?

**Comment by akserg** [comment]
Released yesterday: https://www.npmjs.com/package/ng2-dnd

**Comment by Brocco** [comment]
@akserg I did see it live on npm (using it too) but the confusion may lie in that the release wasn't tagged ;-)

**Comment by akserg** [comment]
Yep. I had a problem with Travis. It didn't publish the build 2.0.0 into the npm repo, so I had to do that manually. The latest build (2.0.1) is tagged.
