### ISSUE TITLE
Source map missing

### ISSUE THREAD

**Issue by linnobita** [akserg/ng2-dnd#68]
After running my site that uses ng2-dnd with angular2 at 2.0.0 on chrome, everything works fine. But when I tried to debug my site, I always see "Failed to parse SourceMap" error messages for all the components of ng2-dnd. And I just search into the ng2-dnd folder inside of node_module folder and found no map files within it. Can you offer the map files? Or is there any workaround?

I installed through my package.json file and the verison of ng2-dnd I'm using is 2.0.1

The error message I've got:
`Failed to parse SourceMap: http://localhost:62275/assets/js/libs/ng2-dnd/src/dnd.utils.js.map
Failed to parse SourceMap: http://localhost:62275/assets/js/libs/ng2-dnd/index.js.map
Failed to parse SourceMap: http://localhost:62275/assets/js/libs/ng2-dnd/src/dnd.config.js.map
Failed to parse SourceMap: http://localhost:62275/assets/js/libs/ng2-dnd/src/dnd.service.js.map
Failed to parse SourceMap: http://localhost:62275/assets/js/libs/ng2-dnd/src/droppable.component.js.map
Failed to parse SourceMap: http://localhost:62275/assets/js/libs/ng2-dnd/src/abstract.component.js.map
Failed to parse SourceMap: http://localhost:62275/assets/js/libs/ng2-dnd/src/draggable.component.js.map
Failed to parse SourceMap: http://localhost:62275/assets/js/libs/ng2-dnd/src/sortable.component.js.map`

**Comment by akserg** [comment]
Fixed. Please use release 2.2.1
