### ISSUE TITLE
AOT Issue

### ISSUE THREAD

**Issue by DarriusWrightGD** [akserg/ng2-dnd#69]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  Feature
- **What is the current behavior?**
  When running ngc there is an error with unexpected value 'DndModule', I believe this is because when using AOT there needs to be a meta.json file for the project. 
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.
  Get an angular AOT project running, install ng2-dnd, and then use ngc
- **What is the expected behavior?**
  No exception.
- **What is the motivation / use case for changing the behavior?**
  So that AOT projects will work.
- **Please tell us about your environment:**
- Angular version: 2.0.0
- Browser: [all]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  Error: Unexpected value 'DndModule' imported by the module

**Comment by ranga543** [comment]
I would love to see this feature as well.

**Comment by mhunting** [comment]
+1 for me as well.

**Comment by Krisa** [comment]
I get a slightly different error, maybe because I call `forRoot()` => `DndModule.forRoot()`... 
> Error encountered resolving symbol values statically. Function calls are not supported.

**Comment by audan2009** [comment]
+1

**Comment by cviccaro** [comment]
Just another voice piling on here, please add support for AOT when you can.

**Comment by inska** [comment]
+1

**Comment by Krisa** [comment]
For those wanting AOT, a workaround is actually to copy the repo in your local src folder and then using the *.ts files instead of the compiled js files. Without additional modification, I could finally use AOT successfully in my project.

**Comment by wuzhouyang** [comment]
resolve？

**Comment by fimbo** [comment]
+1

**Comment by nadavsinai** [comment]
I made [a fork of the repo](https://github.com/Algotec/ng2-dnd) solving this and now made a PR #87

**Comment by rmcsharry** [comment]
@nadavsinai I tried using your repo but I get the same problem (Function calls are not supported blah blah blah).

1. I edited my package.json, to remove the version and directly point to your fork:
`"ng2-dnd": "git://github.com/Algotec/ng2-dnd",`

2. npm install -> you can see the module is removed and then your version gets installed

I try to compile but same error...so how did you get your repo to work?

**Comment by Krisa** [comment]
@rmcsharry 
Indeed, you just need to copy paste the /src/ source folder and the index.ts from this repo, as is:
![image](https://cloud.githubusercontent.com/assets/1253866/21425282/7d4b7d5c-c848-11e6-8838-5617f94cf87e.png)

And then you reference (in my case npm-ng2dnd) instead of the node_modules/ module in your app, and it will just work the same.

**Comment by rmcsharry** [comment]
@Krisa thanks for responding, I have it working now just like you suggested 👍

**Comment by akserg** [comment]
Hi All,
Please, excuse me for the delay. The AOT support implemented in version 2.2.1 and tested in the following projectes:
- [ng2-systemjs-demo](https://github.com/akserg/ng2-systemjs-demo)
- [ng2-webpack-demo](https://github.com/akserg/ng2-webpack-demo) 
Let me know about all issues you will have.

**Comment by rmcsharry** [comment]
@akserg Thanks and Merry Christmas! I have tested 2.2.1 and the simple drag and drop works. I will test sortable dnd tomorrow.

**Comment by akserg** [comment]
Please open the new issue if the problem still exists.
