### ISSUE TITLE
Drop not work with angular2 2.1

### ISSUE THREAD

**Issue by Podkekette** [akserg/ng2-dnd#78]
Hi,

I wanted to implement your module in my project but the behavior is not correct, I explain : The div I want to drop does not drop...

`<div class="container">
    <div class="row">
        <div class="col-xs">
            test
        </div>
        <div class="col-xs" dnd-droppable>
           <div>Place to drop</div>
            <div class="card"  dnd-droppable></div>
        </div>
        <div class="col-xs" dnd-draggable [dragEnabled]="true">
            div to drag
        </div>
    </div>
    <div class="row">
        <div class="col-xs">
            test3
        </div>
        <div class="col-xs">
            1 of 3
        </div>
        <div class="col-xs">
            1 of 3
        </div>
    </div>
</div>`

Thanks :)
Laurent.
- Angular version: 2.1.0

**Comment by paulashford1975** [comment]
I have the same issue on 2.1 I am able to drag the elements but they never drop.

**Comment by roger-schaer** [comment]
Same here with Angular version 2.1.2, I replicated the example code but the drop doesn't react.

**Comment by iinnaann** [comment]
Same problem here :(

**Comment by cviccaro** [comment]
I'm on 2.1.0 and having no problem besides needing AOT.  I think I know what may be tripping you guys up, though.  The sample code doesn't seem to mention you need to add the attribute [dropEnabled]="true" to your drop slots.

**Snippets from my code:**

File drop zone, bootstrap well:
`<div class="drop-area well" dnd-droppable **[dropEnabled]="true"** (onDropSuccess)="onDropSuccess($event)">`

Implementation of google material design chips, drop enabled for doing a swap of the order:   
`<div *ngFor="let option of value; let index = index;"
        class="chip-wrapper"
        dnd-droppable
        (onDragEnter)="onDragEnter($event, index)"
        **[dropEnabled]="true"**
        (onDropSuccess)="reorderFromDrag($event, index)">`

**Comment by roger-schaer** [comment]
@cviccaro Hello Chris,

I tried adding the "dropEnabled" attribute as you suggested, but still none of the functions (onDragEnter, onDropSuccess) are executed. Could you please provide a small Plunker with a working example? It would be much appreciated!

Thanks in advance!

**Comment by gstrit** [comment]
I have the issue. Adding dropEnabled doesn't help.

**Comment by akserg** [comment]
Please try the latest 2.2.1

**Comment by akserg** [comment]
Please open another issue if it still exists.
