### ISSUE TITLE
AOT problem

### ISSUE THREAD

**Issue by wuzhouyang** [akserg/ng2-dnd#84]
i use `DndModule.forRoot()` in my app.module.ts . when i want to build the app with AOT, is throw an error :
![image](https://cloud.githubusercontent.com/assets/12148043/20549047/b72666dc-b163-11e6-97c7-498138bc10d3.png)
so what can i do?

**Comment by wuzhouyang** [comment]
i think you need to add ***.metadata.json*** to support the AOT.   look [angular/angular#11262 (comment)](https://github.com/angular/angular/issues/11262)

**Comment by hansl** [comment]
:+1:. You need to run `ngc` and publish the `metadata.json` file in your NPM package.

We had reports of this library not working with the Angular CLI, but unfortunately there's nothing we can do.

**Comment by rmcsharry** [comment]
28 days ago this branch was created to fix AOT...is anyone able to merge it?

https://github.com/akserg/ng2-dnd/tree/aot

**Comment by akserg** [comment]
Hi All,
Please, excuse me for the delay. The AOT support implemented in version 2.2.1 and tested in the following projects:
- [ng2-systemjs-demo](https://github.com/akserg/ng2-systemjs-demo)
- [ng2-webpack-demo](https://github.com/akserg/ng2-webpack-demo) 
Let me know about all issues you will have.

**Comment by rmcsharry** [comment]
@akserg Thanks and Merry Christmas! I have tested 2.2.1 and the simple drag and drop works. I will test sortable dnd tomorrow.

**Comment by akserg** [comment]
Hi @rmcsharry 
Thank you for you help.

**Comment by rmcsharry** [comment]
BTW, this is duplicate issue, why not close this one and continue to keep 69 open until more people confirm?

https://github.com/akserg/ng2-dnd/issues/69

**Comment by akserg** [comment]
Please open the new issue if the problem still exists.
