### ISSUE TITLE
Guide says to add <ng2-dnd></ng2-dnd> tag but that throws an error

### ISSUE THREAD

**Issue by rmcsharry** [akserg/ng2-dnd#94]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Fails to load, with error in console:

```
Template parse errors:
'ng2-dnd' is not a known element:
1. If 'ng2-dnd' is an Angular component, then verify that it is part of this module.
2. If 'ng2-dnd' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

Add <ng2-dnd></ng2-dnd> tag in template of your application component. <- as per STEP 2 of the readme

* **What is the expected behavior?**

Project builds

* **What is the motivation / use case for changing the behavior?**

Understand if the readme is correct or needs more explanation about where to pug <ng2-dnd></ng2-dnd>

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.X
- Browser: Chrome55

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by akserg** [comment]
Please use the latest 2.2.1

**Comment by rmcsharry** [comment]
I have tried again with the latest and I get the same result. My point here is that the README is not correct. The instructions say:

> 1. Update the markup
> 
> - Import the style.css into your web page
> - Add <ng2-dnd></ng2-dnd> tag in template of your application component.

But if I add the tag, the project crashes. If I DO NOT add the tags, it works fine.

I will create a PR to remove that line from the README, since it is misleading.

**Comment by akserg** [comment]
Agreed.

**Comment by akserg** [comment]
You PR merged.
Thank you.
